In [13]:
# import all packages here

import pandas as pd
import math
import altair as alt
import os

In [18]:
def crptocurrency_data():
    # Set working directory
    os.chdir("/Users/user/Desktop/dashboard-project-cryptocurrency_db")
    # Read databases and add their respective name column
    bitcoin_cash_price = pd.read_csv("raw_data/bitcoin_cash_price.csv")
    bitcoin_cash_price['Name']='bitcoin_cash'
    bitcoin_cash_price.head()

    bitcoin_price = pd.read_csv("raw_data/bitcoin_price.csv")
    bitcoin_price['Name']='bitcoin'
    #bitcoin_price.head()

    bitconnect_price = pd.read_csv("raw_data/bitconnect_price.csv")
    bitconnect_price['Name']='bitconnect'
    #bitconnect_price.head()

    dash_price = pd.read_csv("raw_data/dash_price.csv")
    dash_price['Name']='dash'
    #dash_price.head()

    ethereum_classic_price = pd.read_csv("raw_data/ethereum_classic_price.csv")
    ethereum_classic_price['Name']='ethereum_classic'
    #ethereum_classic_price.head()

    ethereum_price = pd.read_csv("raw_data/ethereum_price.csv")
    ethereum_price['Name']='ethereum'
    #ethereum_price.head()

    iota_price = pd.read_csv("raw_data/iota_price.csv")
    iota_price['Name']='iota'
    #iota_price.head()

    litecoin_price = pd.read_csv("raw_data/litecoin_price.csv")
    litecoin_price['Name']='litecoin'
    #litecoin_price.head()

    monero_price = pd.read_csv("raw_data/monero_price.csv")
    monero_price['Name']='monero'
    #monero_price.head()

    nem_price = pd.read_csv("raw_data/nem_price.csv")
    nem_price['Name']='nem'
    #nem_price.head()

    neo_price = pd.read_csv("raw_data/neo_price.csv")
    neo_price['Name']='neo'
    #neo_price.head()

    numeraire_price = pd.read_csv("raw_data/numeraire_price.csv")
    numeraire_price['Name']='numeraire'
    #numeraire_price.head()

    omisego_price = pd.read_csv("raw_data/omisego_price.csv")
    omisego_price['Name']='omisego'
    #omisego_price.head()

    qtum_price = pd.read_csv("raw_data/qtum_price.csv")
    qtum_price['Name']='qtum'
    #qtum_price.head()

    ripple_price = pd.read_csv("raw_data/ripple_price.csv")
    ripple_price['Name']='ripple'
    #ripple_price.head()

    stratis_price = pd.read_csv("raw_data/stratis_price.csv")
    stratis_price['Name']='stratis'
    #stratis_price.head()

    waves_price = pd.read_csv("raw_data/waves_price.csv")
    waves_price['Name']='waves'
    #waves_price.head()
    
    # Concatenate all the 17 databases
    frames = [bitcoin_cash_price,
              bitcoin_price,
              bitconnect_price, 
              dash_price,
              ethereum_classic_price,
              ethereum_price,
              iota_price,
              litecoin_price,
              monero_price,
              nem_price,
              neo_price,
              numeraire_price,
              omisego_price,
              qtum_price,
              ripple_price,
              stratis_price,
              waves_price]


    price_raw = pd.concat(frames)
    
    return price_raw

In [19]:
crptocurrency_data()

### DATA WRANGLING

In [3]:
# Set working directory
os.chdir("/Users/user/Desktop/dashboard-project-cryptocurrency_db")

In [4]:
# Read databases and add their respective name column
bitcoin_cash_price = pd.read_csv("raw_data/bitcoin_cash_price.csv")
bitcoin_cash_price['Name']='bitcoin_cash'
bitcoin_cash_price.head()

bitcoin_price = pd.read_csv("raw_data/bitcoin_price.csv")
bitcoin_price['Name']='bitcoin'
#bitcoin_price.head()

bitconnect_price = pd.read_csv("raw_data/bitconnect_price.csv")
bitconnect_price['Name']='bitconnect'
#bitconnect_price.head()

dash_price = pd.read_csv("raw_data/dash_price.csv")
dash_price['Name']='dash'
#dash_price.head()

ethereum_classic_price = pd.read_csv("raw_data/ethereum_classic_price.csv")
ethereum_classic_price['Name']='ethereum_classic'
#ethereum_classic_price.head()

ethereum_price = pd.read_csv("raw_data/ethereum_price.csv")
ethereum_price['Name']='ethereum'
#ethereum_price.head()

iota_price = pd.read_csv("raw_data/iota_price.csv")
iota_price['Name']='iota'
#iota_price.head()

litecoin_price = pd.read_csv("raw_data/litecoin_price.csv")
litecoin_price['Name']='litecoin'
#litecoin_price.head()

monero_price = pd.read_csv("raw_data/monero_price.csv")
monero_price['Name']='monero'
#monero_price.head()

nem_price = pd.read_csv("raw_data/nem_price.csv")
nem_price['Name']='nem'
#nem_price.head()

neo_price = pd.read_csv("raw_data/neo_price.csv")
neo_price['Name']='neo'
#neo_price.head()

numeraire_price = pd.read_csv("raw_data/numeraire_price.csv")
numeraire_price['Name']='numeraire'
#numeraire_price.head()

omisego_price = pd.read_csv("raw_data/omisego_price.csv")
omisego_price['Name']='omisego'
#omisego_price.head()

qtum_price = pd.read_csv("raw_data/qtum_price.csv")
qtum_price['Name']='qtum'
#qtum_price.head()

ripple_price = pd.read_csv("raw_data/ripple_price.csv")
ripple_price['Name']='ripple'
#ripple_price.head()

stratis_price = pd.read_csv("raw_data/stratis_price.csv")
stratis_price['Name']='stratis'
#stratis_price.head()

waves_price = pd.read_csv("raw_data/waves_price.csv")
waves_price['Name']='waves'
#waves_price.head()

In [5]:
# Concatenate all the 17 databases
frames = [bitcoin_cash_price,
          bitcoin_price,
          bitconnect_price, 
          dash_price,
          ethereum_classic_price,
          ethereum_price,
          iota_price,
          litecoin_price,
          monero_price,
          nem_price,
          neo_price,
          numeraire_price,
          omisego_price,
          qtum_price,
          ripple_price,
          stratis_price,
          waves_price]


price_raw = pd.concat(frames)

In [12]:
# Drop NA
price_raw2 = price_raw.dropna()
price_raw2

,Date,Open,High,Low,Close,Volume,Market Cap,Name
0,"Feb 20, 2018",1543.270000,1569.03,1414.350000,1418.730000,"820,947,000","26,199,800,000",bitcoin_cash
1,"Feb 19, 2018",1483.340000,1553.81,1483.340000,1534.770000,"578,906,000","25,179,700,000",bitcoin_cash
2,"Feb 18, 2018",1552.100000,1641.40,1428.490000,1487.460000,"907,873,000","26,344,200,000",bitcoin_cash
3,"Feb 17, 2018",1548.480000,1568.64,1517.140000,1551.390000,"641,719,000","26,280,100,000",bitcoin_cash
4,"Feb 16, 2018",1373.160000,1558.66,1369.680000,1552.200000,"961,010,000","23,302,000,000",bitcoin_cash
...,...,...,...,...,...,...,...,...
624,"Jun 06, 2016",0.712541,1.17,0.712541,0.768672,"95,573",-,waves
625,"Jun 05, 2016",0.587588,1.11,0.580745,0.713006,"41,700",-,waves
626,"Jun 04, 2016",1.090000,1.29,0.575898,0.586993,"4,912",-,waves
627,"Jun 03, 2016",1.290000,1.66,0.727579,1.090000,"57,721",-,waves
628,"Jun 02, 2016",1.330000,1.39,1.150000,1.210000,"83,734",-,waves