In [6]:
# import all packages here

import pandas as pd
import math
import altair as alt
import os
import datetime
from time import strptime

### DATA WRANGLING

In [27]:
def crptocurrency_data():
    #Set working directory - Afreen
    os.chdir("/Volumes/UBC/Block5/551/Project_MDS/dashboard-project-cryptocurrency_db")
    
    # Set working directory - Akshita
    #os.chdir("/Users/user/Desktop/dashboard-project-cryptocurrency_db")
   
    
    # Read databases and add their respective name column
    bitcoin_cash_price = pd.read_csv("raw_data/bitcoin_cash_price.csv")
    bitcoin_cash_price['Name']='bitcoin_cash'
    #bitcoin_cash_price.head()

    bitcoin_price = pd.read_csv("raw_data/bitcoin_price.csv")
    bitcoin_price['Name']='bitcoin'
    #bitcoin_price.head()

    bitconnect_price = pd.read_csv("raw_data/bitconnect_price.csv")
    bitconnect_price['Name']='bitconnect'
    #bitconnect_price.head()

    dash_price = pd.read_csv("raw_data/dash_price.csv")
    dash_price['Name']='dash'
    #dash_price.head()

    ethereum_classic_price = pd.read_csv("raw_data/ethereum_classic_price.csv")
    ethereum_classic_price['Name']='ethereum_classic'
    #ethereum_classic_price.head()

    ethereum_price = pd.read_csv("raw_data/ethereum_price.csv")
    ethereum_price['Name']='ethereum'
    #ethereum_price.head()

    iota_price = pd.read_csv("raw_data/iota_price.csv")
    iota_price['Name']='iota'
    #iota_price.head()

    litecoin_price = pd.read_csv("raw_data/litecoin_price.csv")
    litecoin_price['Name']='litecoin'
    #litecoin_price.head()

    monero_price = pd.read_csv("raw_data/monero_price.csv")
    monero_price['Name']='monero'
    #monero_price.head()

    nem_price = pd.read_csv("raw_data/nem_price.csv")
    nem_price['Name']='nem'
    #nem_price.head()

    neo_price = pd.read_csv("raw_data/neo_price.csv")
    neo_price['Name']='neo'
    #neo_price.head()

    numeraire_price = pd.read_csv("raw_data/numeraire_price.csv")
    numeraire_price['Name']='numeraire'
    #numeraire_price.head()

    omisego_price = pd.read_csv("raw_data/omisego_price.csv")
    omisego_price['Name']='omisego'
    #omisego_price.head()

    qtum_price = pd.read_csv("raw_data/qtum_price.csv")
    qtum_price['Name']='qtum'
    #qtum_price.head()

    ripple_price = pd.read_csv("raw_data/ripple_price.csv")
    ripple_price['Name']='ripple'
    #ripple_price.head()

    stratis_price = pd.read_csv("raw_data/stratis_price.csv")
    stratis_price['Name']='stratis'
    #stratis_price.head()

    waves_price = pd.read_csv("raw_data/waves_price.csv")
    waves_price['Name']='waves'
    #waves_price.head()
    
    # Concatenate all the 17 databases
    frames = [bitcoin_cash_price,
              bitcoin_price,
              bitconnect_price, 
              dash_price,
              ethereum_classic_price,
              ethereum_price,
              iota_price,
              litecoin_price,
              monero_price,
              nem_price,
              neo_price,
              numeraire_price,
              omisego_price,
              qtum_price,
              ripple_price,
              stratis_price,
              waves_price]


    price_raw = pd.concat(frames)
    
    # Fix dates
    price_raw['Month_Name'] = price_raw['Date'].str[:3]
    price_raw['Month_Number'] = 0
    price_raw['Date_Number'] = price_raw['Date'].str[4:6]
    price_raw['Year'] = price_raw['Date'].str[8:12]
    price_raw.loc[price_raw['Month_Name'] == "Jan", 'Month_Number'] = 1
    price_raw.loc[price_raw['Month_Name'] == "Feb", 'Month_Number'] = 2
    price_raw.loc[price_raw['Month_Name'] == "Mar", 'Month_Number'] = 3
    price_raw.loc[price_raw['Month_Name'] == "Apr", 'Month_Number'] = 4
    price_raw.loc[price_raw['Month_Name'] == "May", 'Month_Number'] = 5
    price_raw.loc[price_raw['Month_Name'] == "Jun", 'Month_Number'] = 6
    price_raw.loc[price_raw['Month_Name'] == "Jul", 'Month_Number'] = 7
    price_raw.loc[price_raw['Month_Name'] == "Aug", 'Month_Number'] = 8
    price_raw.loc[price_raw['Month_Name'] == "Sep", 'Month_Number'] = 9
    price_raw.loc[price_raw['Month_Name'] == "Oct", 'Month_Number'] = 10
    price_raw.loc[price_raw['Month_Name'] == "Nov", 'Month_Number'] = 11
    price_raw.loc[price_raw['Month_Name'] == "Dec", 'Month_Number'] = 12
    price_raw['Date_Number'] = price_raw['Date_Number'].astype(int)
    price_raw['Year'] = price_raw['Year'].astype(int)
    price_raw['New_date']=(price_raw['Year']*10000)+(price_raw['Month_Number']*100)+(price_raw['Date_Number'])
    price_raw['New_date1']=pd.to_datetime(price_raw['New_date'], format='%Y%m%d')
    #df['dates'] = pd.to_datetime(df['dates'], format='%Y%m%d')
    price_raw = price_raw.sort_values(by=['Name','New_date1'])
    
    price_raw.to_csv('price.csv')
    
    price_raw2 = price_raw[(price_raw.New_date >= 20170120)]
    
    price_raw2.to_csv('price2.csv') #Filtered data
    
    
    return price_raw

In [28]:
crptocurrency_data()

,Date,Open,High,Low,Close,Volume,Market Cap,Name,Month_Name,Month_Number,Date_Number,Year,New_date,New_date1
1759,"Apr 28, 2013",135.30,135.98,132.10,134.21,-,"1,500,520,000",bitcoin,Apr,4,28,2013,20130428,2013-04-28
1758,"Apr 29, 2013",134.44,147.49,134.00,144.54,-,"1,491,160,000",bitcoin,Apr,4,29,2013,20130429,2013-04-29
1757,"Apr 30, 2013",144.00,146.93,134.05,139.00,-,"1,597,780,000",bitcoin,Apr,4,30,2013,20130430,2013-04-30
1756,"May 01, 2013",139.00,139.89,107.72,116.99,-,"1,542,820,000",bitcoin,May,5,1,2013,20130501,2013-05-01
1755,"May 02, 2013",116.38,125.60,92.28,105.21,-,"1,292,190,000",bitcoin,May,5,2,2013,20130502,2013-05-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,"Feb 16, 2018",8.00,8.36,7.49,7.90,"44,143,700","800,093,000",waves,Feb,2,16,2018,20180216,2018-02-16
3,"Feb 17, 2018",7.88,7.96,7.63,7.84,"34,458,200","788,332,000",waves,Feb,2,17,2018,20180217,2018-02-17
2,"Feb 18, 2018",7.84,8.09,7.13,7.54,"40,081,300","784,044,000",waves,Feb,2,18,2018,20180218,2018-02-18
1,"Feb 19, 2018",7.54,8.15,7.44,8.10,"37,813,100","753,733,000",waves,Feb,2,19,2018,20180219,2018-02-19
0,"Feb 20, 2018",8.10,8.49,7.94,8.03,"46,087,500","810,038,000",waves,Feb,2,20,2018,20180220,2018-02-20