In [1]:
# import all packages here

import pandas as pd
import math
import altair as alt
import os

### DATA WRANGLING

In [2]:
# Set working directory
os.chdir("/Volumes/UBC/Block5/551/Project/crypocurrency_db")

In [3]:
# Read databases and add their respective name column
bitcoin_cash_price = pd.read_csv("raw_data/bitcoin_cash_price.csv")
bitcoin_cash_price['Name']='bitcoin_cash'
#bitcoin_cash_price.head()

bitcoin_price = pd.read_csv("raw_data/bitcoin_price.csv")
bitcoin_price['Name']='bitcoin'
#bitcoin_price.head()

bitconnect_price = pd.read_csv("raw_data/bitconnect_price.csv")
bitconnect_price['Name']='bitconnect'
#bitconnect_price.head()

dash_price = pd.read_csv("raw_data/dash_price.csv")
dash_price['Name']='dash'
#dash_price.head()

ethereum_classic_price = pd.read_csv("raw_data/ethereum_classic_price.csv")
ethereum_classic_price['Name']='ethereum_classic'
#ethereum_classic_price.head()

ethereum_price = pd.read_csv("raw_data/ethereum_price.csv")
ethereum_price['Name']='ethereum'
#ethereum_price.head()

iota_price = pd.read_csv("raw_data/iota_price.csv")
iota_price['Name']='iota'
#iota_price.head()

litecoin_price = pd.read_csv("raw_data/litecoin_price.csv")
litecoin_price['Name']='litecoin'
#litecoin_price.head()

monero_price = pd.read_csv("raw_data/monero_price.csv")
monero_price['Name']='monero'
#monero_price.head()

nem_price = pd.read_csv("raw_data/nem_price.csv")
nem_price['Name']='nem'
#nem_price.head()

neo_price = pd.read_csv("raw_data/neo_price.csv")
neo_price['Name']='neo'
#neo_price.head()

numeraire_price = pd.read_csv("raw_data/numeraire_price.csv")
numeraire_price['Name']='numeraire'
#numeraire_price.head()

omisego_price = pd.read_csv("raw_data/omisego_price.csv")
omisego_price['Name']='omisego'
#omisego_price.head()

qtum_price = pd.read_csv("raw_data/qtum_price.csv")
qtum_price['Name']='qtum'
#qtum_price.head()

ripple_price = pd.read_csv("raw_data/ripple_price.csv")
ripple_price['Name']='ripple'
#ripple_price.head()

stratis_price = pd.read_csv("raw_data/stratis_price.csv")
stratis_price['Name']='stratis'
#stratis_price.head()

waves_price = pd.read_csv("raw_data/waves_price.csv")
waves_price['Name']='waves'
#waves_price.head()

In [12]:
# Concatenate all the 17 databases
frames = [bitcoin_cash_price,
          bitcoin_price,
          bitconnect_price, 
          dash_price,
          ethereum_classic_price,
          ethereum_price,
          iota_price,
          litecoin_price,
          monero_price,
          nem_price,
          neo_price,
          numeraire_price,
          omisego_price,
          qtum_price,
          ripple_price,
          stratis_price,
          waves_price]


price_raw = pd.concat(frames)

In [16]:
# Drop NA
price_raw2 = price_raw.dropna()

               Open          High           Low         Close
count  13902.000000  13902.000000  13902.000000  13902.000000
mean     235.377823    245.943390    224.365171    236.360222
std     1168.960357   1224.427501   1104.331094   1172.630090
min        0.000086      0.000089      0.000079      0.000086
25%        0.391338      0.411453      0.373059      0.392836
50%        3.970000      4.135000      3.850000      3.970000
75%       43.135000     45.782500     39.915000     43.377500
max    19475.800000  20089.000000  18974.100000  19497.400000